name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What's wrong?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      value: |
        - [ ] Bug fixed
        - [ ] Functional Spec updated (if behavior changed)
